# Generated by Django 4.1.7 on 2023-03-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answerstudent',
            constraint=models.UniqueConstraint(fields=('student', 'question'), name='unique_student_question'),
        ),
    ]
